### ISSUE TITLE
CONFIG.txt content

### ISSUE THREAD

**Issue by labsin** [andrivet/ADVi3pp-User-Manual#3]
The 01-How-to-Flash.md refers to a Config.txt at **The LCD panel behave strangely..**

`Create a CONFIG.TXT file in the root of a microSD card with the following content:`
 
But the content is not given.

Introduced in: 61577f780779333832dc0020ed896be89778529b
[Github link](https://github.com/andrivet/ADVi3pp-User-Manual/blob/master/01-How-to-Flash.md#the-lcd-panel-behave-strangely-when-you-press-somewhere-it-activates-an-element-at-a-different-place)

**Comment by andrivet** [comment]
Fixed.
