### ISSUE TITLE
Marlin 1.1.8 & .9 / CR10s

### ISSUE THREAD

**Issue by MrDirt** [andrivet/ADVi3pp-User-Manual#6]
Error I receive when trying to compile:
configuration.h:1027:51: error: expected ',' before numeric constant
    #define LEFT_PROBE_BED_POSITION MIN_PROBE_EDGE 20 

My Configuration 
//  Set the boundaries for probing (where the probe can reach).
   #define LEFT_PROBE_BED_POSITION MIN_PROBE_EDGE 20
  #define RIGHT_PROBE_BED_POSITION 240   
   #define FRONT_PROBE_BED_POSITION MIN_PROBE_EDGE 20
   #define BACK_PROBE_BED_POSITION  260

I added my config file 
  
I have watched every youtube video and read everything I could find I have no idea what is going on I would  appreciate any help 

[Configuration.zip](https://github.com/andrivet/ADVi3pp-User-Manual/files/2742701/Configuration.zip)

**Comment by andrivet** [comment]
This is not the right place for support. I am only providing support on Patreon.
